# NUMPY in PYTHON 

In [1]:
# it is introduce by Traivs Oliphant in 2005

In [2]:
import numpy as np

In [5]:
a=np.array([1,4.9,6,7,9])   # auto typecasting 
a

array([1. , 4.9, 6. , 7. , 9. ])

In [7]:
b=np.arange(20)     # Single Dimentions array
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
b.ndim     # ndmin function will get dimentions of the array

1

In [12]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [13]:
c.ndim

2

In [19]:

d=np.arange(30).reshape(5,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
d.shape   # shape is an tribute 

(5, 6)

In [20]:
d.size

30

In [21]:
type(d)

numpy.ndarray

In [23]:
e=np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
#f=np.arange(10).reshape(5,3)  #cannot reshape array of size 10 into shape (5,3)
f=np.arange(15).reshape(5,3) 
f

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
g=np.arange(9).reshape(3,3)
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
h=np.arange(12).reshape(4,3)    #  try 3,4
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
#np.vstack(g,h)   #vstack() takes 1 positional argument but 2 were given

np.vstack((g,h))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
i=np.arange(9).reshape(3,3)
j=np.arange(12).reshape(3,4) 
print(i)
j

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
np.hstack((i,j))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [41]:
np.random.random()   # it will give random numbers

0.17856212085826095

In [47]:
k=np.random.random((2,5))
k

array([[0.33764821, 0.65201552, 0.84492011, 0.13655384, 0.42365371],
       [0.14702532, 0.56307935, 0.85547894, 0.90430349, 0.81719417]])

In [51]:
l=np.floor(100*np.random.random((2,5)))
l

array([[81., 84., 85., 53., 24.],
       [39., 47., 91., 34., 12.]])

In [61]:
np.floor(10.3)

10.0

In [60]:
np.ceil(10.3)

11.0

In [64]:
m=np.floor(100*np.random.random((2,6)))
m

array([[93., 13., 66., 30., 50., 71.],
       [34., 17., 57., 50., 16., 83.]])

In [66]:
print(np.hsplit(m,3))

[array([[93., 13.],
       [34., 17.]]), array([[66., 30.],
       [57., 50.]]), array([[50., 71.],
       [16., 83.]])]


In [67]:
n=np.floor(100*np.random.random((8,2)))


<function numpy.vsplit(ary, indices_or_sections)>

In [68]:
np.vsplit(n,2)

[array([[ 2.,  9.],
        [51., 90.],
        [82., 68.],
        [ 7.,  2.]]), array([[70., 39.],
        [36., 42.],
        [64., 52.],
        [16., 65.]])]

In [70]:
p=np.array([1,2,3,4,5])
p

array([1, 2, 3, 4, 5])

In [71]:
q=p
q              #it will not create copy, it will give reference of it

array([1, 2, 3, 4, 5])

In [72]:
p+q

array([ 2,  4,  6,  8, 10])

In [73]:
p[3]=200

In [74]:
p

array([  1,   2,   3, 200,   5])

In [75]:
q      # since we are referencing 

array([  1,   2,   3, 200,   5])

In [76]:
q=p.copy()

In [79]:
p[3]=400
p

array([  1,   2,   3, 400,   5])

In [81]:
q         # q doent change  as we are giveing as copy 

array([  1,   2,   3, 200,   5])